### ISSUE TITLE
Creating a new message doesn`t give the same result as the list method

### ISSUE THREAD

**Issue by reinos** [jexia-inc/jexia-sdk-js#2]
The response of the create method gives a different object back then the list method for related datasets

Response from the `list()` or `get()` method
```
{
	createdAt: "2016-05-23T10:11:33.389Z",
	id: "5742d755e47559601c5c36a9",
	rel_Field : {
		createdAt: "2016-05-23T10:11:33.376Z",
		id : "5742d755e47559601c5c36a8"
	}
}
```

Response from the `create()` function
```
{
	createdAt: "2016-05-23T10:11:33.389Z",
	id: "5742d755e47559601c5c36a9",
	rel_Field : "5742d755e47559601c5c36a8"
}
```

I think the response of the `get()` and `list()` must be an object and not the ID only.

**Comment by reinos** [comment]
its not related to the sdk, but to the Manager.

**Comment by d3nnn1z** [comment]
Expected behaviour!
This is because the actual application API is returning only the id and not the relational object.
The sdk just returns back the response from the server.
